/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LikedsongPlaylistRouteImport } from './routes/likedsongPlaylist'
import { Route as IndexRouteImport } from './routes/index'

const LikedsongPlaylistRoute = LikedsongPlaylistRouteImport.update({
  id: '/likedsongPlaylist',
  path: '/likedsongPlaylist',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/likedsongPlaylist': typeof LikedsongPlaylistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/likedsongPlaylist': typeof LikedsongPlaylistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/likedsongPlaylist': typeof LikedsongPlaylistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/likedsongPlaylist'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/likedsongPlaylist'
  id: '__root__' | '/' | '/likedsongPlaylist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LikedsongPlaylistRoute: typeof LikedsongPlaylistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/likedsongPlaylist': {
      id: '/likedsongPlaylist'
      path: '/likedsongPlaylist'
      fullPath: '/likedsongPlaylist'
      preLoaderRoute: typeof LikedsongPlaylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LikedsongPlaylistRoute: LikedsongPlaylistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
